#!/bin/bash

ml purge
ml PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4 
ml torchvision/0.7.0-fosscuda-2019b-Python-3.7.4-PyTorch-1.6.0
ml NLTK/3.5-fosscuda-2019b-Python-3.7.4
##ml matplotlib/3.1.1-fosscuda-2019b-Python-3.7.4
##ml
