#!/bin/bash

ml purge
ml GCC/8.3.0
ml CUDA/10.1.243
ml OpenMPI/3.1.4
ml PyTorch/1.6.0-Python-3.7.4
# ml PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4 
ml torchvision/0.7.0-Python-3.7.4-PyTorch-1.6.0
# ml torchvision/0.7.0-fosscuda-2019b-Python-3.7.4-PyTorch-1.6.0
#ml NLTK/3.5-fosscuda-2019b-Python-3.7.4
##ml matplotlib/3.1.1-fosscuda-2019b-Python-3.7.4
##ml
